import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window'); // Get device dimensions

export const styles = StyleSheet.create({
    // Common styles
    gradientScreen: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    safeArea: {
        flex: 1,
        marginTop: 20,
    },
    container: {
        width: '80%',
        marginLeft: '10%',
        marginTop: '35%',
        padding: 20,
        backgroundColor: 'rgba(255,255,255,0.44)',
        borderRadius: 20,
        shadowColor: 'rgba(0,0,0,0)',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        height: 500,
    },
    label: {
        fontSize: 19,
        color: '#000',
        fontWeight: 'bold',
        paddingVertical: 10,
    },
    value: {
        fontSize: 14,
        paddingBottom: 10,
    },
    button: {
        marginTop: 30,
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#FFF',
        alignItems: 'center',
        height: 60,
    },
    buttonText: {
        color: '#FFF',
        fontSize: 26,
        fontWeight: 'bold',
    },
    textTop: {
        fontSize: 18,
        marginLeft: 40,
        marginTop: 10,
    },
    textCont: {
        fontStyle: 'italic',
        fontSize: 14,
        marginTop: 10,
        marginLeft: 60,
    },
    textCont2: {
        fontWeight: 'bold',
        fontSize: 16,
        marginTop: 30,
        marginLeft: 40,
    },
    textLink: {
        marginTop: 20,
        fontSize: 18,
        marginLeft: 60,
    },
    modalContent: {
        backgroundColor: '#a3caca',
        padding: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 15,
        borderColor: 'rgba(0, 0, 0, 0.1)',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    input: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        width: '100%',
    },
    textArea: {
        height: 100,
        borderColor: 'gray',
        borderWidth: 1,
        padding: 10,
        borderRadius: 15,
        marginBottom: 20,
        width: '100%',
    },
    date: {
        marginBottom: 10,
        marginLeft: 130,
        width: '60%',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    buttonContainer2: {
        width: '50%',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    cancelButton: {
        backgroundColor: '#ff4d4d',
    },

    // Styles for ActivityFilter.js
    activityFilterGradientScreen: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    activityFilterSafeArea: {
        flex: 1,
        marginTop: 20,
    },
    activityFilterContainer: {
        width: '80%',
        marginLeft: '10%',
        marginTop: '35%',
        padding: 20,
        backgroundColor: 'rgba(255,255,255,0.44)',
        borderRadius: 20,
        shadowColor: 'rgba(0,0,0,0)',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        height: 500,
    },
    activityFilterSlider: {
        width: '100%',
    },
    activityFilterPicker: {
        marginTop: 10,
        width: '100%',
        height: 80,
        borderRadius: 15,
        backgroundColor: 'rgba(248,248,248,0.47)',
    },
    activityFilterPickerItem: {
        alignItems: 'center',
        height: 80,
    },
    activityFilterLabel: {
        fontSize: 19,
        color: '#000',
        fontWeight: 'bold',
        paddingVertical: 10,
    },
    activityFilterValue: {
        fontSize: 14,
        paddingBottom: 10,
    },
    activityFilterButton: {
        marginTop: 30,
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#FFF',
        alignItems: 'center',
        height: 60,
    },
    activityFilterButtonText: {
        color: '#FFF',
        fontSize: 26,
        fontWeight: 'bold',
    },

    // Styles for Activities.js
    activitiesGradientScreen: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    activitiesSafeArea: {
        flex: 1,
        marginTop: 140,
        marginBottom: 100,
    },
    activitiesContainer: {
        margin: 10,
        padding: 20,
        backgroundColor: 'rgba(255,255,255,0.63)',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#1e1d1d',
    },
    activitiesTitle: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    activitiesDetails: {
        marginTop: 10,
    },
    activitiesActivityIndicator: {
        top: 300,
    },
    activitiesErrorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    activitiesErrorText: {
        color: 'red',
        fontSize: 16,
    },
    activitiesNoResultsContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    activitiesNoResultsText: {
        fontSize: 16,
        textAlign: 'center',
        marginTop: 20,
    },
    activitiesAddButton: {
        marginTop: 40,
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        marginLeft: '25%',
    },
    activitiesAddButtonText: {
        color: 'white',
        fontSize: 16,
    },
    activitiesTextTop: {
        fontSize: 18,
        marginLeft: 40,
        marginTop: 10,
    },
    activitiesTextCont: {
        fontStyle: 'italic',
        fontSize: 14,
        marginTop: 10,
        marginLeft: 60,
    },
    activitiesTextCont2: {
        fontWeight: 'bold',
        fontSize: 16,
        marginTop: 30,
        marginLeft: 40,
    },
    activitiesTextLink: {
        marginTop: 20,
        fontSize: 18,
        marginLeft: 60,
    },
    activitiesModalContent: {
        backgroundColor: '#a3caca',
        padding: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 15,
        borderColor: 'rgba(0, 0, 0, 0.1)',
    },
    activitiesModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    activitiesInput: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        width: '100%',
    },
    activitiesTextArea: {
        height: 100,
        borderColor: 'gray',
        borderWidth: 1,
        padding: 10,
        borderRadius: 15,
        marginBottom: 20,
        width: '100%',
    },
    activitiesDate: {
        marginBottom: 10,
        marginLeft: 130,
        width: '60%',
    },
    activitiesButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    activitiesButtonContainer2: {
        width: '50%',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    activitiesButton: {
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        flex: 1,
        marginHorizontal: 5,
    },
    activitiesCancelButton: {
        backgroundColor: '#ff4d4d',
    },
    activitiesButtonText: {
        color: 'white',
        fontSize: 16,
    },

    // Styles for ActivityFeed.js
    activityFeedContainer: {
        flex: 1,
        top: 0,
        alignItems: 'center',
    },
    activityFeedListContainer: {
        paddingBottom: 20,
    },
    activityFeedSectionTitle: {
        fontSize: 20,
        fontFamily: 'Roboto-Bold',
        color: '#FFECE7',
        marginTop: 20,
        marginBottom: 10,
    },

    // Styles for ActivityItem.js
    activityItemContainer: {
        backgroundColor: '#4a90e2',
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
        flexDirection: 'column',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
    },
    activityItemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    activityItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    activityItemProfileImage: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 10,
    },
    activityItemTextContainer: {
        flex: 1,
    },
    activityItemFeedText: {
        color: '#FFECE7',
        fontSize: 16,
        marginRight: 20,
    },
    activityItemIconsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    activityItemIconContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 0,
    },

    // Styles for SearchVenn.js
    searchVennGradientScreen: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchVennSafeArea: {
        flex: 1,
        marginTop: 20,
    },
    searchVennContainer: {
        width: '80%',
        marginLeft: '10%',
        marginTop: '35%',
        padding: 20,
        backgroundColor: 'rgba(255,255,255,0.44)',
        borderRadius: 20,
        shadowColor: 'rgba(0,0,0,0)',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        height: 500,
    },
    searchVennLabel: {
        fontSize: 25,
        color: '#000',
        fontWeight: 'bold',
        marginBottom: 50,
        paddingVertical: 10,
    },
    searchVennButton: {
        marginTop: 30,
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#FFF',
        alignItems: 'center',
        height: 60,
    },
    searchVennButtonText: {
        color: '#FFF',
        fontSize: 26,
        fontWeight: 'bold',
    },

    // Styles for AddVenn.js
    addVennGradientScreen: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addVennSafeArea: {
        flex: 1,
        marginTop: 20,
    },
    addVennContainer: {
        margin: 10,
        padding: 20,
        backgroundColor: 'rgba(255,255,255,0.63)',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#1e1d1d',
    },
    addVennTitle: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    addVennDetails: {
        marginTop: 10,
    },
    addVennActivityIndicator: {
        top: 300,
    },
    addVennErrorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    addVennErrorText: {
        color: 'red',
        fontSize: 16,
    },
    addVennNoResultsContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    addVennNoResultsText: {
        fontSize: 16,
        textAlign: 'center',
        marginTop: 20,
    },
    addVennAddButton: {
        marginTop: 40,
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        marginLeft: '25%',
    },
    addVennAddButtonText: {
        color: 'white',
        fontSize: 16,
    },
    addVennTextTop: {
        fontSize: 18,
        marginLeft: 40,
        marginTop: 10,
    },
    addVennTextCont: {
        fontStyle: 'italic',
        fontSize: 14,
        marginTop: 10,
        marginLeft: 60,
    },
    addVennTextCont2: {
        fontWeight: 'bold',
        fontSize: 16,
        marginTop: 30,
        marginLeft: 40,
    },
    addVennTextLink: {
        marginTop: 20,
        fontSize: 18,
        marginLeft: 60,
    },
    addVennModalContent: {
        backgroundColor: '#a3caca',
        padding: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 15,
        borderColor: 'rgba(0, 0, 0, 0.1)',
    },
    addVennModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    addVennInput: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        width: '100%',
    },
    addVennTextArea: {
        height: 100,
        borderColor: 'gray',
        borderWidth: 1,
        padding: 10,
        borderRadius: 15,
        marginBottom: 20,
        width: '100%',
    },
    addVennDate: {
        marginBottom: 10,
        marginLeft: 130,
        width: '60%',
    },
    addVennButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    addVennButtonContainer2: {
        width: '50%',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    addVennButton: {
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        flex: 1,
        marginHorizontal: 5,
    },
    addVennCancelButton: {
        backgroundColor: '#ff4d4d',
    },
    addVennButtonText: {
        color: 'white',
        fontSize: 16,
    },

    // Styles for FriendRequests.js
    friendRequestsContainer: {
        marginTop: 20,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderRadius: 10,
        borderColor: '#FFECE7',
        width: '60%',
        alignSelf: 'center',
    },
    friendRequestsSectionTitle: {
        fontSize: 20,
        fontFamily: 'Roboto-Bold',
        color: '#FFECE7',
        marginTop: 20,
        marginBottom: 10,
    },
    friendRequestsFeedListContainer: {
        paddingBottom: 20,
    },

    // Styles for FriendsList.js
    friendsListContainer: {
        marginTop: 20,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderRadius: 10,
        borderColor: '#FFECE7',
        width: '60%',
        alignSelf: 'center',
    },
    friendsListSectionTitle: {
        fontSize: 20,
        fontFamily: 'Roboto-Bold',
        color: '#FFECE7',
        marginTop: 20,
        marginBottom: 10,
    },
    friendsListFeedListContainer: {
        paddingBottom: 20,
    },
    friendsListItem: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#FFECE7',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    friendsListItemProfileImage: {
        width: 50,
        height: 50,
        borderRadius: 50,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#FFECE7',
        marginRight: 10,
        marginTop: 10,
    },
    friendsListItemText: {
        color: '#FFECE7',
        fontSize: 16,
        marginRight: 20,
    },

    // Styles for Add.js
    addContainer: {
        width: '90%',
        margin: '5%',
        padding: 20,
        marginTop: 20,
        height: '90%',
        backgroundColor: 'rgba(255,255,255,0.49)',
        borderRadius: 20,
        shadowColor: 'rgba(0,0,0,0.2)',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        overflow: 'visible',
    },
    addRowContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 60,
        marginTop: 40,
        zIndex: 1,
    },
    addInput: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderRadius: 10,
        marginBottom: 10,
        fontSize: 20,
    },
    addDateText: {
        fontSize: 20,
        textAlign: 'center',
    },
    addDate: {
        width: '60%',
        marginLeft: '40%',
    },
    addLabel: {
        fontSize: 18,
        marginBottom: 10,
        fontWeight: 'bold',
    },
    addLabel1: {
        fontSize: 18,
        marginBottom: 50,
        fontWeight: 'bold',
    },
    addLabelContainer: {
        marginRight: 40,
    },
    addTextArea: {
        height: 100,
        borderColor: 'gray',
        borderWidth: 1,
        padding: 10,
        borderRadius: 10,
        marginBottom: 70,
        fontSize: 18,
    },
    addButton: {
        backgroundColor: '#008080',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    addButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    addPickerContainer: {
        backgroundColor: 'rgb(255,255,255)',
        padding: 10,
        width: '60%',
        height: 'auto',
        borderRadius: 10,
        marginBottom: 10,
        position: 'absolute',
        top: 1,
        zIndex: 1000,
    },
    addItem: {
        padding: 10,
        fontSize: 18,
    },
    addSelectedItem: {
        padding: 10,
        fontSize: 18,
        backgroundColor: 'lightgray',
    },

    // Styles for Calendar.js
    calendarContainer: {
        margin: 10,
        padding: 20,
        marginTop: 130,
        height: 600,
        backgroundColor: 'rgba(255,255,255,0.63)',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#1e1d1d',
    },
    calendarTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 40,
    },
    calendarStyle: {
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#1e1d1d',
        height: 400,
    },
    calendarModalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    calendarModalContainer: {
        width: '80%',
        padding: 20,
        backgroundColor: '#fbf0f0',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
    },
    calendarModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    calendarModalText: {
        color: '#333',
        fontSize: 18,
        marginBottom: 10,
    },
    calendarModalCloseButton: {
        marginTop: 10,
        padding: 10,
        backgroundColor: '#ddd',
        alignItems: 'center',
        borderRadius: 10,
    },

    // Styles for Profil.js
    profilContainer: {
        flex: 1,
    },
    profilMenuButton: {
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: '#FFECE7',
        borderWidth: 2,
        borderRadius: 10,
        height: 50,
        width: 50,
        position: 'absolute',
        top: '24%',
        right: '5%',
        zIndex: 1,
    },
    profilHeader: {
        alignItems: 'center',
        paddingTop: 160,
        paddingBottom: 20,
        backgroundColor: 'transparent',
    },
    profilImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#FFECE7',
    },
    profilImagePlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 20,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#FFECE7',
    },
    profilAddPictureIcon: {
        fontSize: 40,
        color: '#FFECE7',
    },
    profilUserName: {
        fontSize: 24,
        fontFamily: 'Roboto-Bold',
        color: '#faf3f2',
    },
    profilSettingsDetails: {
        alignItems: 'center',
        marginTop: 10,
    },
    profilSettingText: {
        fontSize: 14,
        fontFamily: 'Roboto-Regular',
        color: '#FFECE7',
        marginBottom: 10,
    },

    // Styles for ProfilLoggInn.js
    profilLoggInnContainer: {
        flex: 1,
    },
    profilLoggInnInputLabel: {
        fontFamily: 'Roboto-Medium',
        fontSize: 16,
        color: '#FFECE7',
        position: 'absolute',
    },
    profilLoggInnInputGroup: {
        position: 'absolute',
        width: 238,
        right: 332,
        height: 50.7,
        borderRadius: 10,
        backgroundColor: '#FFECE7',
    },
    profilLoggInnForgotPassword: {
        color: '#FFECE7',
        fontSize: 15,
        fontFamily: 'Roboto-Medium',
        position: 'absolute',
    },
    profilLoggInnButton: {
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: '#FFECE7',
        borderWidth: 2,
        borderRadius: 10,
        height: 50,
        position: 'absolute',
        width: 177,
    },
    profilLoggInnItalicText: {
        fontSize: 18,
        fontFamily: 'Roboto-Italic',
        color: '#FFECE7',
        ...Platform.select({
            ios: {
                shadowColor: '#000000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.25,
                shadowRadius: 4,
            },
            android: {
                shadowColor: '#000000',
                elevation: 4,
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.25,
                shadowRadius: 4,
            },
            web: {},
        }),
        position: 'absolute',
    },

    // Styles for ProfilRegistrering.js
    profilRegistreringContainer: {
        flex: 1,
    },
    profilRegistreringInputLabel: {
        fontFamily: 'Roboto-Medium',
        fontSize: 16,
        color: '#FFECE7',
        position: 'absolute',
    },
    profilRegistreringInputGroup: {
        position: 'absolute',
        width: 238,
        right: 332,
        height: 50.7,
        borderRadius: 10,
        backgroundColor: '#FFECE7',
    },
    profilRegistreringButton: {
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: '#FFECE7',
        borderWidth: 2,
        borderRadius: 10,
        height: 50,
        position: 'absolute',
        width: 177,
    },
    profilRegistreringItalicText: {
        fontSize: 18,
        fontFamily: 'Roboto-Italic',
        color: '#FFECE7',
        ...Platform.select({
            ios: {
                shadowColor: '#000000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.25,
                shadowRadius: 4,
            },
            android: {
                shadowColor: '#000000',
                elevation: 4,
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.25,
                shadowRadius: 4,
            },
            web: {},
        }),
        position: 'absolute',
    },

    // Styles for ProfilSettings.js
    profilSettingsContainer: {
        flex: 1,
        marginTop: 20,
    },
    profilSettingsScrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    profilSettingsContentContainer: {
        flexGrow: 1,
        width: '80%',
        paddingBottom: 100, // Adjust as needed to ensure scrolling area doesn't overlap with the bottom tab
    },
    profilSettingsInputGroup2: {
        width: 238,
        marginVertical: 10,
        alignSelf: 'center',
        backgroundColor: '#FFECE7',
        borderRadius: 10,
    },
    profilSettingsButtonContainer2: {
        width: '50%',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    profilSettingsButton: {
        backgroundColor: '#008080',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        flex: 1,
        marginHorizontal: 5,
    },
    profilSettingsCancelButton: {
        backgroundColor: '#ff4d4d',
    },
    profilSettingsButtonText: {
        color: 'white',
        fontSize: 16,
    },

    // Styles for FriendRequestItem.js
    friendRequestItemContainer: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#FFECE7',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    friendRequestItemProfileImage: {
        width: 50,
        height: 50,
        borderRadius: 50,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#FFECE7',
        marginRight: 10,
        marginTop: 10,
    },
    friendRequestItemText: {
        color: '#FFECE7',
        fontSize: 16,
        marginRight: 20,
    },
    friendRequestItemAcceptButton: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderColor: '#FFECE7',
        borderWidth: 2,
        borderRadius: 15,
    }
});